version: '3.8'
name: nuxter

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vue-ai_production_app_caddy
      - vue-ai_staging_app_caddy
      - vue-ai_production_db_caddy
      - vue-ai_staging_db_caddy
      - vue-ai_umami_caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  vue-ai_production_app_caddy:
    name: vue-ai_production_app_caddy
    external: true
  vue-ai_staging_app_caddy:
    name: vue-ai_staging_app_caddy
    external: true
  vue-ai_production_db_caddy:
    name: vue-ai_production_db_caddy
    external: true
  vue-ai_staging_db_caddy:
    name: vue-ai_staging_db_caddy
    external: true
  vue-ai_umami_caddy:
    name: vue-ai_umami_caddy
    external: true