version: '3.8'
name: nuxter-server

services:
  node:
    image: node:18-alpine
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - .output:/home/node/app
    command: 'node server/index.mjs'

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: