version: '3.8'
name: nuxter

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vue-tools-ai_production_caddy_nuxt_app
      - vue-tools-ai_staging_caddy_nuxt_app
      - vue-tools-ai_production_caddy_pb_db
      - vue-tools-ai_staging_caddy_pb_db
      - vue-tools-ai_umami_caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  vue-tools-ai_production_caddy_nuxt_app:
    name: vue-tools-ai_production_caddy_nuxt_app
    external: true
  vue-tools-ai_staging_caddy_nuxt_app:
    name: vue-tools-ai_staging_caddy_nuxt_app
    external: true
  vue-tools-ai_production_caddy_pb_db:
    name: vue-tools-ai_production_caddy_pb_db
    external: true
  vue-tools-ai_staging_caddy_pb_db:
    name: vue-tools-ai_staging_caddy_pb_db
    external: true
  vue-tools-ai_umami_caddy:
    name: vue-tools-ai_umami_caddy
    external: true