version: '3.8'
name: nuxter-server

services:
  node:
    image: node:18-alpine
    build: .
    restart: unless-stopped

  caddy:
    image: caddy:latest
    depends_on:
      - node
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: