version: '3.8'
name: nuxter-server

services:
  node-production:
    build: 
      context: .
      args:
        REPO_URL: https://github.com/chris-paganon/vue-tools-ai.git
        REPO_BRANCH: master
    restart: unless-stopped
  
  node-staging:
    build: 
      context: .
      args:
        REPO_URL: https://github.com/chris-paganon/vue-tools-ai.git
        REPO_BRANCH: stage
    restart: unless-stopped

  caddy:
    image: caddy:latest
    depends_on:
      - node-production
      - node-staging
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: