version: '3.8'
name: nuxter

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - vue-ai_caddy_network

volumes:
  caddy_data:
  caddy_config:

networks:
  vue-ai_caddy_network:
    name: vue-ai_caddy_network
    external: true