version: '3.8'

services:
  node-production:
    build: 
      context: .
      dockerfile: Dockerfile.apps
      args:
        REPO_URL: https://github.com/chris-paganon/vue-tools-ai.git
        REPO_BRANCH: master
    restart: unless-stopped
  
  node-staging:
    build: 
      context: .
      dockerfile: Dockerfile.apps
      args:
        REPO_URL: https://github.com/chris-paganon/vue-tools-ai.git
        REPO_BRANCH: stage
    restart: unless-stopped