version: '3.8'
name: nuxter-db-vueai

services:
  db-production:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data

  db-staging:
    build: 
      context: .
      dockerfile: Dockerfile.db
    restart: unless-stopped
    volumes:
      - staging-pb_data:/pb/pb_data

volumes:
  pb_data:
  staging-pb_data: