version: '3.8'

services:
  node-production:
    container_name: ${APP_NAME}-node-production
    build: 
      context: .
      dockerfile: Dockerfile.apps
      args:
        REPO_URL: ${REPO_URL}
        REPO_BRANCH: master
    restart: unless-stopped
    networks:
      - production_app_caddy
  
  node-staging:
    container_name: ${APP_NAME}-node-staging
    build: 
      context: .
      dockerfile: Dockerfile.apps
      args:
        REPO_URL: ${REPO_URL}
        REPO_BRANCH: stage
    restart: unless-stopped
    networks:
      - staging_app_caddy

networks:
  production_app_caddy:
    name: ${APP_NAME}_production_app_caddy
    external: true
  staging_app_caddy:
    name: ${APP_NAME}_staging_app_caddy
    external: true