version: '3.8'

services:
  node:
    container_name: ${APP_NAME}-node-${APP_ENV}
    build: 
      context: .
      dockerfile: Dockerfile.apps
      args:
        APP_NAME: ${APP_NAME}
        REPO_URL: ${REPO_URL}
        REPO_BRANCH: ${REPO_BRANCH}
    env_file: ../${APP_NAME}/${APP_ENV}.env
    restart: unless-stopped
    networks:
      - app_caddy

networks:
  app_caddy:
    name: ${APP_NAME}_${APP_ENV}_app_caddy
    external: true