version: '3.8'

services:
  db-production:
    container_name: ${APP_NAME}-db-production
    build: 
      context: .
      dockerfile: Dockerfile.db
      args:
        PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY}
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - production_db_caddy

  db-staging:
    container_name: ${APP_NAME}-db-staging
    build: 
      context: .
      dockerfile: Dockerfile.db
      args:
        PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY}
    restart: unless-stopped
    volumes:
      - staging-pb_data:/pb/pb_data
    networks:
      - staging_db_caddy

volumes:
  pb_data:
  staging-pb_data:
  
networks:
  production_db_caddy:
    name: ${APP_NAME}_production_db_caddy
    external: true
  staging_db_caddy:
    name: ${APP_NAME}_staging_db_caddy
    external: true