version: '3.8'

services:
  db:
    container_name: ${APP_NAME}-db-${APP_ENV}
    build: 
      context: .
      dockerfile: Dockerfile.db
      args:
        PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY}
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - db_caddy

volumes:
  pb_data:
    name: ${APP_NAME}_${APP_ENV}_pb_data
  
networks:
  db_caddy:
    name: ${APP_NAME}_${APP_ENV}_db_caddy
    external: true