version: '3.8'

services:
  nuxt-app:
    container_name: ${APP_NAME}-${APP_ENV}-nuxt-app
    build: 
      context: .
      dockerfile: Dockerfile.nuxt-app
      args:
        APP_NAME: ${APP_NAME}
        REPO_URL: ${REPO_URL}
        REPO_BRANCH: ${REPO_BRANCH}
    env_file: ../${APP_NAME}/${APP_ENV}.env
    restart: unless-stopped
    networks:
      - caddy_nuxt_app

networks:
  caddy_nuxt_app:
    name: ${APP_NAME}_${APP_ENV}_caddy_nuxt_app
    external: true