version: '3.8'

services:
  pb-db:
    container_name: ${APP_NAME}-${APP_ENV}-pb-db
    build: 
      context: .
      dockerfile: base/Dockerfile.pb-db
      args:
        PB_ENCRYPTION_KEY: ${PB_ENCRYPTION_KEY}
        APP_NAME: ${APP_NAME}
    restart: unless-stopped
    volumes:
      - pb_data:/pb/pb_data
    networks:
      - caddy_pb_db

volumes:
  pb_data:
    name: ${APP_NAME}_${APP_ENV}_pb_data
  
networks:
  caddy_pb_db:
    name: ${APP_NAME}_${APP_ENV}_caddy_pb_db
    external: true