version: '3.8'

services:
  umami:
    container_name: ${APP_NAME}-umami
    image: ghcr.io/umami-software/umami:postgresql-latest
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: umami_secret
    depends_on:
      umami-db:
        condition: service_healthy
    restart: always
    networks:
      - umami_caddy
      - umami_db

  umami-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - umami_db

volumes:
  umami-db-data:

secrets:
  umami_secret:
    file: ./umami_secret.env
    
networks:
  umami_caddy:
    name: ${APP_NAME}_umami_caddy
    external: true
  umami_db: