on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  push-changes:
    name: Push changes to master
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and pull git
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_KEY }}
          script: |
            cd /opt/nuxter
            git checkout master
            git pull
